=== 408apple/scsh-scripts/globaltester/suite/testcase.dtd
<?xml version="1.0" encoding="ISO-8859-1"?>
<!ELEMENT testsuite (testsuiteid, version, date, author, company, shortdescription, description, references, globalpreconditions, testcase)>
<!ELEMENT testsuiteid (#PCDATA)>
<!ELEMENT version (#PCDATA)>
<!ELEMENT date (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT company (#PCDATA)>
<!ELEMENT shortdescription (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT references (#PCDATA)>
<!ELEMENT globalpreconditions (#PCDATA)>
<!ELEMENT testcase (testcaseid, shortdescription, description, quality, preconditions, testscript, postconditions)>
<!ELEMENT testcaseid (#PCDATA)>
<!ELEMENT quality (#PCDATA)>
<!ELEMENT preconditions (#PCDATA)>
<!ELEMENT testscript (#PCDATA)>
<!ELEMENT postconditions (condition+)>
<!ELEMENT condition (#PCDATA)>

=== 408apple/scsh-scripts/globaltester/suite/GT_TestCase_2.xml
<?xml version="1.0" encoding="ISO-8859-1" standalone="no"?>
<!DOCTYPE testsuite SYSTEM "testcase.dtd"[]>
<?xml-stylesheet type="text/xsl" href="testcase.xsl" ?>

<testsuite>

  <testsuiteid>SuiteID</testsuiteid>
  <version>1.0</version>
  <date>2007-11-02</date>
  <author>Andreas Schwier</author>
  <company>OpenSCDP</company>
  <shortdescription>
	Testcase Example
  </shortdescription>
  <description>
	Testcase Example
  </description>
  <references>  </references>
  <globalpreconditions>
  
  </globalpreconditions>

  <testcase>
	<testcaseid>TC2</testcaseid>
	<shortdescription>Testcase 2</shortdescription>
	<description>
		Testcase Example 2
	</description>
	<quality>Mandatory</quality>

	<preconditions><![CDATA[
		print("Section precondition executing...");
		load("../lib/TestSetup.js");
	]]></preconditions>
	
	<testscript><![CDATA[
		print("Section testscript executing...");
	]]></testscript>

	<postconditions>
		<condition><![CDATA[
		print("Section condition 1 executing...");
	]]></condition>
		<condition><![CDATA[
		print("Section condition 2 executing...");
	]]></condition>
		<condition><![CDATA[
		print("Section condition 3 executing (will fail)...");
		throw new GPError("GTTest", 0, 0, "Test failed");
	]]></condition>
	</postconditions>
  </testcase>
</testsuite>
